version:  '3.7'
services:
    mysql:
        container_name: lithuania_project_mysql
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - ${MYSQL_PORT}:3306
    php:
        container_name: lithuania_project_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - ./:/var/www/project/
        user: ${LOCAL_USER}
    nginx:
        container_name: lithuania_project_nginx
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - ./:/var/www/project/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - ${NGINX_PORT}:80
        depends_on:
            - php
    encore:
        container_name: lithuania_project_node
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        volumes:
            - .:/var/www/project/
        ports:
            - "${DEV_SERVER_PORT:-8000}:8000"
        working_dir: /var/www/project/
        command: sh -c "tail -f /dev/null"